export type user = {
    accountFinancialDetails: null;
    refreshToken: string;
    refreshTokenExpiryTime: string;
    registrationDateTime: string;
    displayName: string;
    avatarUrl: null;
    orders: null;
    id: number;
    userName: string;
    normalizedUserName: string;
    email: string;
    normalizedEmail: string;
    emailConfirmed: boolean;
    passwordHash: string;
    securityStamp: string;
    concurrencyStamp: string;
    phoneNumber: null;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled: boolean;
    lockoutEnd: null;
    lockoutEnabled: boolean;
    accessFailedCount: number;
};
